<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1578474755622" stop="1578474755622">
  <description>This is the tests collection phase. Failures are modules that failed to collect.</description>
  <name>test_collection_phase</name>
  <title>Collection phase</title>
  <labels/>
  <test-cases>
    <test-case start="1578474755622" status="broken" stop="1578474755622">
      <name>test02_mp_article</name>
      <failure>
        <message>failed</message>
        <stack-trace>test02_mp_article.py:2: in &lt;module&gt;
    from page.page_in import PageIn
..\page\page_in.py:1: in &lt;module&gt;
    from page.page_mp_article import PageMpArticle
..\page\page_mp_article.py:3: in &lt;module&gt;
    from base.base import Base
..\base\base.py:7: in &lt;module&gt;
    log = GetLog.get_logger()
..\tools\get_log.py:17: in get_logger
    encoding="utf-8")
C:\Users\VULCAN\AppData\Local\Programs\Python\Python36-32\lib\logging\handlers.py:202: in __init__
    BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
C:\Users\VULCAN\AppData\Local\Programs\Python\Python36-32\lib\logging\handlers.py:57: in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
C:\Users\VULCAN\AppData\Local\Programs\Python\Python36-32\lib\logging\__init__.py:1030: in __init__
    StreamHandler.__init__(self, self._open())
C:\Users\VULCAN\AppData\Local\Programs\Python\Python36-32\lib\logging\__init__.py:1059: in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
E   FileNotFoundError: [Errno 2] No such file or directory: 'D:\\feiq\\Recv Files\\UiHMTTAutoItem(4)\\scripts\\log\\hmtt.log'</stack-trace>
      </failure>
      <attachments/>
      <labels/>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
